name: db_update

on: 
  schedule:
    - cron: '*/56 * * * *'

    # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs: 
  build:
    runs-on: ubuntu-latest
    steps:

      - name: checkout repo content
        uses: actions/checkout@v2

      - name: setup node
        uses: actions/setup-node@v2
        with:
            node-version: '14'
            cache: 'npm'
            cache-dependency-path: package-lock.json


      - name: install npm
        run: npm install
        
      - name: install tes
        run: npm test
          
      - name: execute node script
        run: node test.js

      # - name: commit files
      #   run: |
      #     git config --local user.email "emailmeit@protonmail.com"
      #     git config --local user.name "GitHub Action"
      #     git add -A
      #     git commit -m "update base data from Parallel site" -a

      # - name: push changes
      #   uses: ad-m/github-push-action@v0.6.0
      #   with: 
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     branch: main  
